---
grafana_version: 12.2.1
grafana_admin_user: admin
grafana_admin_password: nondefaultpassword
grafana_port: 3000

prometheus_version: 3.5.0
prometheus_port: 9090

otel_version: 0.138.0
otel_http_receiver_port: 4242
otel_prometheus_exporter_port: 8999

loki_port: 3100
loki_version: 3.5.7

tempo_port: 3200
tempo_version: 2.9.0
